-- AlterTable
ALTER TABLE `bffdata` MODIFY `cs1` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs2` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs3` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs4` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs5` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs6` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `tmidata` MODIFY `tmiSubType` VARCHAR(191) NULL,
    MODIFY `cs1` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs2` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs3` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs4` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs5` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cs6` INTEGER NOT NULL DEFAULT 0;
